-- Question 2: Insert five employees information.
INSERT INTO EMPLOYEE VALUES (1,'JOHN DOE', 'MUMBAI');
INSERT INTO EMPLOYEE VALUES (2, 'TERENCE AUSTIN', 'MANIPAL');
INSERT INTO EMPLOYEE VALUES (3, 'BARCLAY COOPER', 'DELHI');
INSERT INTO EMPLOYEE VALUES (4, 'KEN APPLE', 'MANIPAL');
INSERT INTO EMPLOYEE VALUES (5, 'THORA DIXON', 'MANGALORE');
